// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/inca/inca.proto

package inca

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import peer "github.com/aperturerobotics/bifrost/peer"
import cid "github.com/aperturerobotics/hydra/cid"
import _ "github.com/aperturerobotics/objectsig"
import timestamp "github.com/aperturerobotics/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NodeMessageType identifies the purpose of the node message.
// Additional types may be declared elsewhere.
type NodeMessageType int32

const (
	NodeMessageType_NodeMessageType_UNKNOWN      NodeMessageType = 0
	NodeMessageType_NodeMessageType_VOTE         NodeMessageType = 1
	NodeMessageType_NodeMessageType_BLOCK_COMMIT NodeMessageType = 2
	NodeMessageType_NodeMessageType_APP          NodeMessageType = 3
)

var NodeMessageType_name = map[int32]string{
	0: "NodeMessageType_UNKNOWN",
	1: "NodeMessageType_VOTE",
	2: "NodeMessageType_BLOCK_COMMIT",
	3: "NodeMessageType_APP",
}
var NodeMessageType_value = map[string]int32{
	"NodeMessageType_UNKNOWN":      0,
	"NodeMessageType_VOTE":         1,
	"NodeMessageType_BLOCK_COMMIT": 2,
	"NodeMessageType_APP":          3,
}

func (x NodeMessageType) String() string {
	return proto.EnumName(NodeMessageType_name, int32(x))
}
func (NodeMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{0}
}

// OperationMode is the operation mode of the validator.
type Validator_OperationMode int32

const (
	// OperationMode_STAGING indicates the validator is not currently online.
	// A validator can voluntarily step-down for some time this way.
	// The validator can step up by voting on a block.
	Validator_OperationMode_STAGING Validator_OperationMode = 0
	// OperationMode_OPERATING indicates the validator is currently operating.
	Validator_OperationMode_OPERATING Validator_OperationMode = 1
)

var Validator_OperationMode_name = map[int32]string{
	0: "OperationMode_STAGING",
	1: "OperationMode_OPERATING",
}
var Validator_OperationMode_value = map[string]int32{
	"OperationMode_STAGING":   0,
	"OperationMode_OPERATING": 1,
}

func (x Validator_OperationMode) String() string {
	return proto.EnumName(Validator_OperationMode_name, int32(x))
}
func (Validator_OperationMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{0, 0}
}

// Validator holds information about a validator.
type Validator struct {
	// PubKey is the validator's public key.
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// VotingPower is the voting power of the validator.
	VotingPower uint64 `protobuf:"varint,2,opt,name=voting_power,json=votingPower" json:"voting_power,omitempty"`
	// OperationMode is the operation mode of the validator.
	OperationMode        Validator_OperationMode `protobuf:"varint,3,opt,name=operation_mode,json=operationMode,enum=inca.Validator_OperationMode" json:"operation_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (dst *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(dst, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Validator) GetVotingPower() uint64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *Validator) GetOperationMode() Validator_OperationMode {
	if m != nil {
		return m.OperationMode
	}
	return Validator_OperationMode_STAGING
}

// ValidatorSet is a set of validators.
type ValidatorSet struct {
	// Validators are the address to validator object pairings. Validators are
	// sorted by crc32 of pubkey and voting power (little endian) concatinated.
	// Object: Validator
	Validators           []*Validator `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{1}
}
func (m *ValidatorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSet.Unmarshal(m, b)
}
func (m *ValidatorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSet.Marshal(b, m, deterministic)
}
func (dst *ValidatorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSet.Merge(dst, src)
}
func (m *ValidatorSet) XXX_Size() int {
	return xxx_messageInfo_ValidatorSet.Size(m)
}
func (m *ValidatorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSet.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSet proto.InternalMessageInfo

func (m *ValidatorSet) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

// Block is a committed block in the chain.
type Block struct {
	// BlockHeaderRef is the reference to the block header.
	BlockHeaderRef *cid.BlockRef `protobuf:"bytes,1,opt,name=block_header_ref,json=blockHeaderRef" json:"block_header_ref,omitempty"`
	// VoteRefs are the validator votes included to justify this block. The block
	// header must be identical across the votes and equal to the block_header_ref
	// in the Block.
	VoteRefs             []*cid.BlockRef `protobuf:"bytes,2,rep,name=vote_refs,json=voteRefs" json:"vote_refs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{2}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockHeaderRef() *cid.BlockRef {
	if m != nil {
		return m.BlockHeaderRef
	}
	return nil
}

func (m *Block) GetVoteRefs() []*cid.BlockRef {
	if m != nil {
		return m.VoteRefs
	}
	return nil
}

// BlockHeader is the header of a block.
type BlockHeader struct {
	// GenesisRef contains a reference to the Genesis object.
	GenesisRef *cid.BlockRef `protobuf:"bytes,1,opt,name=genesis_ref,json=genesisRef" json:"genesis_ref,omitempty"`
	// ChainConfigRef contains a reference to the ChainConfig object.
	ChainConfigRef *cid.BlockRef `protobuf:"bytes,2,opt,name=chain_config_ref,json=chainConfigRef" json:"chain_config_ref,omitempty"`
	// NextChainConfigRef contains a reference to the next ChainConfig object. The
	// entire next BlockHeader must then be written within BlockRef range of the
	// next chain config. Field should be empty if equal to chain_config_ref.
	NextChainConfigRef *cid.BlockRef `protobuf:"bytes,3,opt,name=next_chain_config_ref,json=nextChainConfigRef" json:"next_chain_config_ref,omitempty"`
	// PrevBlockRef contains a reference to the prev Block object.
	PrevBlockRef *cid.BlockRef `protobuf:"bytes,4,opt,name=prev_block_ref,json=prevBlockRef" json:"prev_block_ref,omitempty"`
	// RoundInfo contains the round information.
	RoundInfo *BlockRoundInfo `protobuf:"bytes,5,opt,name=round_info,json=roundInfo" json:"round_info,omitempty"`
	// BlockTs is the timestamp the block header was proposed.
	BlockTs *timestamp.Timestamp `protobuf:"bytes,6,opt,name=block_ts,json=blockTs" json:"block_ts,omitempty"`
	// ValidatorIndex is the index in the ValidatorSet of the proposer.
	ValidatorIndex uint32 `protobuf:"varint,7,opt,name=validator_index,json=validatorIndex" json:"validator_index,omitempty"`
	// StateRef is the reference to the application state.
	StateRef             *cid.BlockRef `protobuf:"bytes,8,opt,name=state_ref,json=stateRef" json:"state_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{3}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetGenesisRef() *cid.BlockRef {
	if m != nil {
		return m.GenesisRef
	}
	return nil
}

func (m *BlockHeader) GetChainConfigRef() *cid.BlockRef {
	if m != nil {
		return m.ChainConfigRef
	}
	return nil
}

func (m *BlockHeader) GetNextChainConfigRef() *cid.BlockRef {
	if m != nil {
		return m.NextChainConfigRef
	}
	return nil
}

func (m *BlockHeader) GetPrevBlockRef() *cid.BlockRef {
	if m != nil {
		return m.PrevBlockRef
	}
	return nil
}

func (m *BlockHeader) GetRoundInfo() *BlockRoundInfo {
	if m != nil {
		return m.RoundInfo
	}
	return nil
}

func (m *BlockHeader) GetBlockTs() *timestamp.Timestamp {
	if m != nil {
		return m.BlockTs
	}
	return nil
}

func (m *BlockHeader) GetValidatorIndex() uint32 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

func (m *BlockHeader) GetStateRef() *cid.BlockRef {
	if m != nil {
		return m.StateRef
	}
	return nil
}

// BlockRoundInfo contains information about the round.
type BlockRoundInfo struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Round                uint64   `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRoundInfo) Reset()         { *m = BlockRoundInfo{} }
func (m *BlockRoundInfo) String() string { return proto.CompactTextString(m) }
func (*BlockRoundInfo) ProtoMessage()    {}
func (*BlockRoundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{4}
}
func (m *BlockRoundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRoundInfo.Unmarshal(m, b)
}
func (m *BlockRoundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRoundInfo.Marshal(b, m, deterministic)
}
func (dst *BlockRoundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRoundInfo.Merge(dst, src)
}
func (m *BlockRoundInfo) XXX_Size() int {
	return xxx_messageInfo_BlockRoundInfo.Size(m)
}
func (m *BlockRoundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRoundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRoundInfo proto.InternalMessageInfo

func (m *BlockRoundInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockRoundInfo) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

// Vote is a signature on a proposal by a validator.
type Vote struct {
	// ValidatorIndex is the index in the ValidatorSet of the voter. Refers to the
	// block_header_ref->prev_block_ref ValidatorSet index. The ValidatorSet for
	// the previous block is always used when voting for a new block.
	ValidatorIndex uint32 `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex" json:"validator_index,omitempty"`
	// ValidatorSignature contains the signature of the validator.
	// The data signed is the encoded block_header_ref.
	// The PubKey field should be empty.
	// The PubKey should be inferred from the validator index.
	ValidatorSignature   *peer.Signature `protobuf:"bytes,2,opt,name=validator_signature,json=validatorSignature" json:"validator_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{5}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (dst *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(dst, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetValidatorIndex() uint32 {
	if m != nil {
		return m.ValidatorIndex
	}
	return 0
}

func (m *Vote) GetValidatorSignature() *peer.Signature {
	if m != nil {
		return m.ValidatorSignature
	}
	return nil
}

// Genesis is the initial object starting the blockchain.
type Genesis struct {
	// ChainId is used to differentiate between chains, but could be set to anything.
	// It is an opaque value and ignored by the system.
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	// Timestamp contains the time the genesis block was formed.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// InitChainConfig is the initial chain configuration.
	InitChainConfigRef   *cid.BlockRef `protobuf:"bytes,3,opt,name=init_chain_config_ref,json=initChainConfigRef" json:"init_chain_config_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Genesis) Reset()         { *m = Genesis{} }
func (m *Genesis) String() string { return proto.CompactTextString(m) }
func (*Genesis) ProtoMessage()    {}
func (*Genesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{6}
}
func (m *Genesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genesis.Unmarshal(m, b)
}
func (m *Genesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genesis.Marshal(b, m, deterministic)
}
func (dst *Genesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genesis.Merge(dst, src)
}
func (m *Genesis) XXX_Size() int {
	return xxx_messageInfo_Genesis.Size(m)
}
func (m *Genesis) XXX_DiscardUnknown() {
	xxx_messageInfo_Genesis.DiscardUnknown(m)
}

var xxx_messageInfo_Genesis proto.InternalMessageInfo

func (m *Genesis) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Genesis) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Genesis) GetInitChainConfigRef() *cid.BlockRef {
	if m != nil {
		return m.InitChainConfigRef
	}
	return nil
}

// ChainConfig is the configuration for the blockchain. Can be updated each block.
type ChainConfig struct {
	// TimingConfig contains the timing configuration.
	TimingConfig *TimingConfig `protobuf:"bytes,1,opt,name=timing_config,json=timingConfig" json:"timing_config,omitempty"`
	// ValidatorSetRef contains a reference to the computed validator set.
	ValidatorSetRef      *cid.BlockRef `protobuf:"bytes,2,opt,name=validator_set_ref,json=validatorSetRef" json:"validator_set_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChainConfig) Reset()         { *m = ChainConfig{} }
func (m *ChainConfig) String() string { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()    {}
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{7}
}
func (m *ChainConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainConfig.Unmarshal(m, b)
}
func (m *ChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainConfig.Marshal(b, m, deterministic)
}
func (dst *ChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfig.Merge(dst, src)
}
func (m *ChainConfig) XXX_Size() int {
	return xxx_messageInfo_ChainConfig.Size(m)
}
func (m *ChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfig proto.InternalMessageInfo

func (m *ChainConfig) GetTimingConfig() *TimingConfig {
	if m != nil {
		return m.TimingConfig
	}
	return nil
}

func (m *ChainConfig) GetValidatorSetRef() *cid.BlockRef {
	if m != nil {
		return m.ValidatorSetRef
	}
	return nil
}

// TimingConfig is the timing configuration for the blockchain.
// Timings are in milliseconds (ms).
type TimingConfig struct {
	// MinProposeAfterBlock is the minimum time after a block before the next round starts.
	// The round starts at block[i-1].Timestamp + MinProposeAfterBlock
	// Minimum: 0.
	// Unit: milliseconds
	MinProposeAfterBlock uint32 `protobuf:"varint,1,opt,name=min_propose_after_block,json=minProposeAfterBlock" json:"min_propose_after_block,omitempty"`
	// RoundLength is the length of each round.
	// Minimum: 100ms.
	// Unit: milliseconds
	RoundLength          uint32   `protobuf:"varint,3,opt,name=round_length,json=roundLength" json:"round_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimingConfig) Reset()         { *m = TimingConfig{} }
func (m *TimingConfig) String() string { return proto.CompactTextString(m) }
func (*TimingConfig) ProtoMessage()    {}
func (*TimingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{8}
}
func (m *TimingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimingConfig.Unmarshal(m, b)
}
func (m *TimingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimingConfig.Marshal(b, m, deterministic)
}
func (dst *TimingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimingConfig.Merge(dst, src)
}
func (m *TimingConfig) XXX_Size() int {
	return xxx_messageInfo_TimingConfig.Size(m)
}
func (m *TimingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TimingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TimingConfig proto.InternalMessageInfo

func (m *TimingConfig) GetMinProposeAfterBlock() uint32 {
	if m != nil {
		return m.MinProposeAfterBlock
	}
	return 0
}

func (m *TimingConfig) GetRoundLength() uint32 {
	if m != nil {
		return m.RoundLength
	}
	return 0
}

// NodeMessage is a message submitted to the network by a peer.
// The node is identified by the pubsub transport.
type NodeMessage struct {
	// GenesisRef contains a reference to the Genesis object.
	GenesisRef *cid.BlockRef `protobuf:"bytes,1,opt,name=genesis_ref,json=genesisRef" json:"genesis_ref,omitempty"`
	// PrevMsgRef is the reference to the previous NodeMessage.
	PrevMsgRef *cid.BlockRef `protobuf:"bytes,2,opt,name=prev_msg_ref,json=prevMsgRef" json:"prev_msg_ref,omitempty"`
	// Timestamp is the timestamp of this NodeMessage.
	// The timestamp must be after the timestamp of the previous message.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// InnerRef is the reference to the inner object sent in this message.
	InnerRef *cid.BlockRef `protobuf:"bytes,4,opt,name=inner_ref,json=innerRef" json:"inner_ref,omitempty"`
	// MessageType is the type of message this is.
	MessageType NodeMessageType `protobuf:"varint,5,opt,name=message_type,json=messageType,enum=inca.NodeMessageType" json:"message_type,omitempty"`
	// AppMessageType is filled to identify the inner app message type.
	AppMessageType       uint32   `protobuf:"varint,6,opt,name=app_message_type,json=appMessageType" json:"app_message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMessage) Reset()         { *m = NodeMessage{} }
func (m *NodeMessage) String() string { return proto.CompactTextString(m) }
func (*NodeMessage) ProtoMessage()    {}
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{9}
}
func (m *NodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMessage.Unmarshal(m, b)
}
func (m *NodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMessage.Marshal(b, m, deterministic)
}
func (dst *NodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMessage.Merge(dst, src)
}
func (m *NodeMessage) XXX_Size() int {
	return xxx_messageInfo_NodeMessage.Size(m)
}
func (m *NodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMessage proto.InternalMessageInfo

func (m *NodeMessage) GetGenesisRef() *cid.BlockRef {
	if m != nil {
		return m.GenesisRef
	}
	return nil
}

func (m *NodeMessage) GetPrevMsgRef() *cid.BlockRef {
	if m != nil {
		return m.PrevMsgRef
	}
	return nil
}

func (m *NodeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NodeMessage) GetInnerRef() *cid.BlockRef {
	if m != nil {
		return m.InnerRef
	}
	return nil
}

func (m *NodeMessage) GetMessageType() NodeMessageType {
	if m != nil {
		return m.MessageType
	}
	return NodeMessageType_NodeMessageType_UNKNOWN
}

func (m *NodeMessage) GetAppMessageType() uint32 {
	if m != nil {
		return m.AppMessageType
	}
	return 0
}

// ChainPubsubMessage is a message emitted by a node in the chain pubsub channel.
type ChainPubsubMessage struct {
	// NodeMessageRef contains a reference to the node message being sent.
	NodeMessageRef *cid.BlockRef `protobuf:"bytes,1,opt,name=node_message_ref,json=nodeMessageRef" json:"node_message_ref,omitempty"`
	// PeerId is the peer ID encoded in base58
	PeerId               string   `protobuf:"bytes,2,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainPubsubMessage) Reset()         { *m = ChainPubsubMessage{} }
func (m *ChainPubsubMessage) String() string { return proto.CompactTextString(m) }
func (*ChainPubsubMessage) ProtoMessage()    {}
func (*ChainPubsubMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_inca_1336df5d1b6f026c, []int{10}
}
func (m *ChainPubsubMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainPubsubMessage.Unmarshal(m, b)
}
func (m *ChainPubsubMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainPubsubMessage.Marshal(b, m, deterministic)
}
func (dst *ChainPubsubMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainPubsubMessage.Merge(dst, src)
}
func (m *ChainPubsubMessage) XXX_Size() int {
	return xxx_messageInfo_ChainPubsubMessage.Size(m)
}
func (m *ChainPubsubMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainPubsubMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChainPubsubMessage proto.InternalMessageInfo

func (m *ChainPubsubMessage) GetNodeMessageRef() *cid.BlockRef {
	if m != nil {
		return m.NodeMessageRef
	}
	return nil
}

func (m *ChainPubsubMessage) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func init() {
	proto.RegisterType((*Validator)(nil), "inca.Validator")
	proto.RegisterType((*ValidatorSet)(nil), "inca.ValidatorSet")
	proto.RegisterType((*Block)(nil), "inca.Block")
	proto.RegisterType((*BlockHeader)(nil), "inca.BlockHeader")
	proto.RegisterType((*BlockRoundInfo)(nil), "inca.BlockRoundInfo")
	proto.RegisterType((*Vote)(nil), "inca.Vote")
	proto.RegisterType((*Genesis)(nil), "inca.Genesis")
	proto.RegisterType((*ChainConfig)(nil), "inca.ChainConfig")
	proto.RegisterType((*TimingConfig)(nil), "inca.TimingConfig")
	proto.RegisterType((*NodeMessage)(nil), "inca.NodeMessage")
	proto.RegisterType((*ChainPubsubMessage)(nil), "inca.ChainPubsubMessage")
	proto.RegisterEnum("inca.NodeMessageType", NodeMessageType_name, NodeMessageType_value)
	proto.RegisterEnum("inca.Validator_OperationMode", Validator_OperationMode_name, Validator_OperationMode_value)
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/inca/inca.proto", fileDescriptor_inca_1336df5d1b6f026c)
}

var fileDescriptor_inca_1336df5d1b6f026c = []byte{
	// 943 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdb, 0x6e, 0xe3, 0x36,
	0x13, 0x5e, 0xd9, 0x89, 0x63, 0x8f, 0x0f, 0xf1, 0xcf, 0x4d, 0xfe, 0x68, 0xb7, 0x2d, 0xe0, 0xd5,
	0x4d, 0x8d, 0x14, 0xb0, 0x01, 0x07, 0x8b, 0xb4, 0x37, 0xed, 0x26, 0xe9, 0x22, 0x35, 0xb2, 0x3e,
	0x40, 0x71, 0xd3, 0x4b, 0x41, 0xb2, 0x46, 0x36, 0xbb, 0x11, 0xa9, 0x8a, 0x74, 0xba, 0xbe, 0x2c,
	0xfa, 0x16, 0x7d, 0x82, 0x5e, 0xf7, 0x61, 0xfa, 0x3c, 0x05, 0x49, 0xf9, 0x58, 0x27, 0x48, 0x2f,
	0x6c, 0x70, 0x66, 0xbe, 0x8f, 0x1c, 0xcd, 0xcc, 0x47, 0xc2, 0x57, 0x13, 0x2a, 0xa7, 0xb3, 0xa0,
	0x35, 0xe6, 0x71, 0xdb, 0x4f, 0x30, 0x95, 0xb3, 0x14, 0x53, 0x1e, 0x70, 0x49, 0xc7, 0xa2, 0x4d,
	0xd9, 0xd8, 0xd7, 0x7f, 0xad, 0x24, 0xe5, 0x92, 0x93, 0x3d, 0xb5, 0x7e, 0x7d, 0xf6, 0x14, 0x25,
	0xa0, 0x51, 0xca, 0x85, 0x6c, 0x27, 0x88, 0xa9, 0xfe, 0x33, 0xd4, 0xd7, 0xed, 0xa7, 0x48, 0xd3,
	0x79, 0x98, 0xfa, 0xed, 0x31, 0x0d, 0xd5, 0x2f, 0x23, 0xbc, 0x7d, 0x8a, 0x20, 0x69, 0x8c, 0x42,
	0xfa, 0x71, 0xb2, 0x5a, 0x3d, 0x87, 0xc6, 0x83, 0x9f, 0x71, 0x2c, 0x05, 0x9d, 0xac, 0x56, 0x86,
	0xe6, 0xfc, 0x6d, 0x41, 0xe9, 0xce, 0xbf, 0xa7, 0xa1, 0x2f, 0x79, 0x4a, 0x4e, 0xe0, 0x20, 0x99,
	0x05, 0xde, 0x47, 0x9c, 0xdb, 0x56, 0xc3, 0x6a, 0x56, 0xdc, 0x42, 0x32, 0x0b, 0x6e, 0x70, 0x4e,
	0xde, 0x40, 0xe5, 0x81, 0x4b, 0xca, 0x26, 0x5e, 0xc2, 0x7f, 0xc5, 0xd4, 0xce, 0x35, 0xac, 0xe6,
	0x9e, 0x5b, 0x36, 0xbe, 0xa1, 0x72, 0x91, 0xef, 0xa1, 0xc6, 0x13, 0x4c, 0x7d, 0x49, 0x39, 0xf3,
	0x62, 0x1e, 0xa2, 0x9d, 0x6f, 0x58, 0xcd, 0x5a, 0xe7, 0x8b, 0x96, 0x2e, 0xe4, 0xf2, 0x90, 0xd6,
	0x60, 0x81, 0xea, 0xf1, 0x10, 0xdd, 0x2a, 0x5f, 0x37, 0x9d, 0x6b, 0xa8, 0x6e, 0xc4, 0xc9, 0x2b,
	0x38, 0xde, 0x70, 0x78, 0xb7, 0xa3, 0x8b, 0xeb, 0x6e, 0xff, 0xba, 0xfe, 0x82, 0x7c, 0x06, 0x27,
	0x9b, 0xa1, 0xc1, 0xf0, 0xbd, 0x7b, 0x31, 0x52, 0x41, 0xcb, 0xf9, 0x0e, 0x2a, 0xcb, 0x23, 0x6f,
	0x51, 0x92, 0x36, 0xc0, 0xc3, 0xc2, 0x16, 0xb6, 0xd5, 0xc8, 0x37, 0xcb, 0x9d, 0xc3, 0xad, 0xd4,
	0xdc, 0x35, 0x88, 0x73, 0x0f, 0xfb, 0x97, 0xf7, 0x7c, 0xfc, 0x91, 0x9c, 0x43, 0x3d, 0x50, 0x0b,
	0x6f, 0x8a, 0x7e, 0x88, 0xa9, 0x97, 0x62, 0xa4, 0xab, 0x53, 0xee, 0x54, 0x5b, 0xaa, 0x6d, 0x1a,
	0xe5, 0x62, 0xe4, 0xd6, 0x34, 0xec, 0x07, 0x8d, 0x72, 0x31, 0x22, 0xa7, 0x50, 0x7a, 0xe0, 0x12,
	0x15, 0x41, 0xd8, 0x39, 0x7d, 0xe2, 0x16, 0xa3, 0xa8, 0xe2, 0x2e, 0x46, 0xc2, 0xf9, 0x33, 0x0f,
	0xe5, 0xcb, 0x15, 0x9d, 0xb4, 0xa0, 0x3c, 0x41, 0x86, 0x82, 0x8a, 0xc7, 0xcf, 0x83, 0x0c, 0xa1,
	0xce, 0x3a, 0x87, 0xfa, 0x78, 0xea, 0x53, 0xe6, 0x8d, 0x39, 0x8b, 0xe8, 0x44, 0x93, 0x72, 0x3b,
	0x93, 0xd4, 0xb0, 0x2b, 0x8d, 0x52, 0xc4, 0x77, 0x70, 0xcc, 0xf0, 0x93, 0xf4, 0xfe, 0xc5, 0xce,
	0xef, 0x62, 0x13, 0x85, 0xbd, 0xda, 0xdc, 0xe1, 0x0c, 0x6a, 0x49, 0x8a, 0x0f, 0x9e, 0x29, 0x92,
	0xa2, 0xee, 0xed, 0xa2, 0x56, 0x14, 0x68, 0x61, 0x91, 0x33, 0x80, 0x94, 0xcf, 0x58, 0xe8, 0x51,
	0x16, 0x71, 0x7b, 0x5f, 0x13, 0x8e, 0x4c, 0x3b, 0x0c, 0x46, 0x05, 0xbb, 0x2c, 0xe2, 0x6e, 0x29,
	0x5d, 0x2c, 0x49, 0x1b, 0x8a, 0xe6, 0x10, 0x29, 0xec, 0x42, 0x46, 0x59, 0xe9, 0x60, 0xb4, 0x58,
	0xb9, 0x07, 0x1a, 0x35, 0x12, 0xe4, 0x4b, 0x38, 0x5c, 0x76, 0xd4, 0xa3, 0x2c, 0xc4, 0x4f, 0xf6,
	0x41, 0xc3, 0x6a, 0x56, 0xdd, 0xda, 0xd2, 0xdd, 0x55, 0x5e, 0xd5, 0x2a, 0x21, 0x7d, 0xd3, 0x2b,
	0xbb, 0xb8, 0x2b, 0xfd, 0xa2, 0x8e, 0xbb, 0x18, 0x39, 0xdf, 0x42, 0x6d, 0x33, 0x45, 0xf2, 0x7f,
	0x28, 0x4c, 0x91, 0x4e, 0xa6, 0x52, 0xf7, 0x69, 0xcf, 0xcd, 0x2c, 0x72, 0x04, 0xfb, 0x3a, 0xf9,
	0x4c, 0x2e, 0xc6, 0x70, 0x7e, 0x81, 0xbd, 0x3b, 0x2e, 0x71, 0x57, 0x72, 0xd6, 0xce, 0xe4, 0xde,
	0xc1, 0xcb, 0x15, 0x50, 0xd0, 0x09, 0xf3, 0x95, 0xb8, 0xb3, 0xf6, 0x1e, 0xb6, 0xf4, 0x65, 0x73,
	0xbb, 0x70, 0xbb, 0x64, 0x89, 0x5d, 0xfa, 0x9c, 0x3f, 0x2c, 0x38, 0xb8, 0x36, 0xc3, 0x42, 0x5e,
	0x41, 0xd1, 0xf4, 0x9a, 0x86, 0xfa, 0xbc, 0x92, 0x7b, 0xa0, 0xed, 0x6e, 0x48, 0x3a, 0x50, 0x5a,
	0x96, 0x33, 0xdb, 0x7e, 0x77, 0x81, 0x57, 0x30, 0x35, 0x3f, 0x94, 0xd1, 0x67, 0xcf, 0x8f, 0xc2,
	0x6e, 0xce, 0x8f, 0xf3, 0x9b, 0x05, 0xe5, 0x35, 0x17, 0x39, 0x87, 0xaa, 0xa4, 0xb1, 0xba, 0x6b,
	0xcc, 0x6e, 0xd9, 0xf0, 0x13, 0x33, 0x1d, 0x23, 0x1d, 0xca, 0xd8, 0x15, 0xb9, 0x66, 0x91, 0x6f,
	0xe0, 0x7f, 0x6b, 0x75, 0x42, 0xf9, 0xb8, 0x08, 0x56, 0x85, 0xbf, 0x45, 0xa9, 0x72, 0x98, 0x42,
	0x65, 0x7d, 0x63, 0xf2, 0x16, 0x4e, 0x62, 0xca, 0xbc, 0x24, 0xe5, 0x09, 0x17, 0xe8, 0xf9, 0x91,
	0xc4, 0xd4, 0x0c, 0x78, 0xd6, 0xa3, 0xa3, 0x98, 0xb2, 0xa1, 0x89, 0x5e, 0xa8, 0xa0, 0xb9, 0x2a,
	0xde, 0x40, 0xc5, 0x4c, 0xf5, 0x3d, 0xb2, 0x89, 0x9c, 0xea, 0x1a, 0x54, 0xdd, 0xb2, 0xf6, 0x7d,
	0xd0, 0x2e, 0xe7, 0xaf, 0x1c, 0x94, 0xfb, 0x3c, 0xc4, 0x1e, 0x0a, 0xe1, 0x4f, 0xf0, 0x3f, 0x0b,
	0xbd, 0x0d, 0x5a, 0x48, 0x5e, 0x2c, 0x9e, 0x10, 0x39, 0x28, 0x48, 0x4f, 0x68, 0x79, 0x6e, 0x34,
	0x35, 0xff, 0xbc, 0xa6, 0x9e, 0x42, 0x89, 0x32, 0x96, 0xdd, 0x75, 0x3b, 0xd5, 0x5c, 0xd4, 0x71,
	0xb5, 0xff, 0xd7, 0x50, 0x89, 0xcd, 0xb7, 0x78, 0x72, 0x9e, 0xa0, 0xd6, 0x72, 0xad, 0x73, 0x6c,
	0xba, 0xb5, 0xf6, 0xa5, 0xa3, 0x79, 0x82, 0x6e, 0x39, 0x5e, 0x19, 0xa4, 0x09, 0x75, 0x3f, 0x49,
	0xbc, 0x0d, 0x76, 0xc1, 0x28, 0xc0, 0x4f, 0x92, 0x35, 0x9a, 0x13, 0x01, 0xd1, 0x13, 0x32, 0x9c,
	0x05, 0x62, 0x16, 0x2c, 0x4a, 0x77, 0x0e, 0x75, 0xa6, 0xae, 0xfd, 0xc5, 0x06, 0x8f, 0x5f, 0xcc,
	0x6c, 0x95, 0x86, 0x4a, 0x59, 0x3d, 0x73, 0x88, 0xa9, 0x52, 0x40, 0x4e, 0x2b, 0xa0, 0xa0, 0xcc,
	0x6e, 0x78, 0xfa, 0xbb, 0x05, 0x87, 0x5b, 0x29, 0xab, 0x57, 0x66, 0xcb, 0xe5, 0xfd, 0xd8, 0xbf,
	0xe9, 0x0f, 0x7e, 0xea, 0xd7, 0x5f, 0x10, 0x1b, 0x8e, 0xb6, 0x83, 0x77, 0x83, 0xd1, 0xfb, 0xba,
	0x45, 0x1a, 0xf0, 0xf9, 0x76, 0xe4, 0xf2, 0xc3, 0xe0, 0xea, 0xc6, 0xbb, 0x1a, 0xf4, 0x7a, 0xdd,
	0x51, 0x3d, 0x47, 0x4e, 0xe0, 0xe5, 0x36, 0xe2, 0x62, 0x38, 0xac, 0xe7, 0x83, 0x82, 0x7e, 0x9a,
	0xcf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x54, 0x28, 0x01, 0x3c, 0xa3, 0x08, 0x00, 0x00,
}
