// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/inca/chain/validator.proto

package chain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import inca "github.com/aperturerobotics/inca"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ValidatorState is state for a validator.
type ValidatorState struct {
	LastVote             *inca.BlockRoundInfo `protobuf:"bytes,1,opt,name=last_vote,json=lastVote" json:"last_vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ValidatorState) Reset()         { *m = ValidatorState{} }
func (m *ValidatorState) String() string { return proto.CompactTextString(m) }
func (*ValidatorState) ProtoMessage()    {}
func (*ValidatorState) Descriptor() ([]byte, []int) {
	return fileDescriptor_validator_8968b77a9e44de9d, []int{0}
}
func (m *ValidatorState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorState.Unmarshal(m, b)
}
func (m *ValidatorState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorState.Marshal(b, m, deterministic)
}
func (dst *ValidatorState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorState.Merge(dst, src)
}
func (m *ValidatorState) XXX_Size() int {
	return xxx_messageInfo_ValidatorState.Size(m)
}
func (m *ValidatorState) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorState.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorState proto.InternalMessageInfo

func (m *ValidatorState) GetLastVote() *inca.BlockRoundInfo {
	if m != nil {
		return m.LastVote
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidatorState)(nil), "chain.ValidatorState")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/inca/chain/validator.proto", fileDescriptor_validator_8968b77a9e44de9d)
}

var fileDescriptor_validator_8968b77a9e44de9d = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0xcf, 0xcc, 0x4b, 0x4e, 0xd4, 0x4f, 0xce, 0x48,
	0xcc, 0xcc, 0xd3, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x05, 0x0b, 0x4b, 0x69, 0x13, 0xd4, 0x0e, 0x22, 0x20, 0x7a, 0x94, 0x9c,
	0xb9, 0xf8, 0xc2, 0x60, 0xc6, 0x04, 0x97, 0x24, 0x96, 0xa4, 0x0a, 0x19, 0x72, 0x71, 0xe6, 0x24,
	0x16, 0x97, 0xc4, 0x97, 0xe5, 0x97, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8,
	0x81, 0x75, 0x38, 0xe5, 0xe4, 0x27, 0x67, 0x07, 0xe5, 0x97, 0xe6, 0xa5, 0x78, 0xe6, 0xa5, 0xe5,
	0x07, 0x71, 0x80, 0x94, 0x85, 0xe5, 0x97, 0xa4, 0x26, 0xb1, 0x81, 0xcd, 0x32, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x13, 0x33, 0xde, 0xca, 0xb9, 0x00, 0x00, 0x00,
}
